# definitions of keywords
CKT_BEGIN = ".circuit"
CKT_END = ".end"
COM_RESISTOR = "R"
COM_INDUCTOR = "L"
COM_CAPACITOR = "C"
SRC_V = "V"
SRC_C = "I"
DEP_SRC_VCVS = "E"
DEP_SRC_VCCS = "G"
DEP_SRC_CCVS = "H"
DEP_SRC_CCCS = "F"